<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

//Event constants for Authorization
//LM
define('NAME_CORR_LM_FIRST', 'NMECORRLMFIRST');
define('NAME_CORR_LM_REVERT', 'NMECORRLMREVERT');
define('NAME_CANC_LM_FIRST', 'NMECANCLMFIRST');
define('NAME_CANC_LM_REVERT', 'NMECANCLMREVERT');
define('CCS_LM_FIRST', 'CCSLMFIRST');
define('CCS_LM_REVERT', 'CCSLMREVERT');
define('CONV_LM_FIRST', 'CONVLMFIRST');
define('CONV_LM_RVRT_CO_SECOND', 'CONVLMRVRTCOSECOND');
// define('CONV_LM_RVRT_DCEND', 'CONVLMRVRTDCEND');

//CO
define('NAME_CORR_CO_FIRST', 'NMECORRCOFIRST');
define('NAME_CORR_CO_SECOND', 'NMECORRCOSECOND');
define('NAME_CANC_CO_FIRST', 'NMECANCCOFIRST');
define('NAME_CANC_CO_SECOND', 'NMECANCCOSECOND');
define('CCS_CO_FIRST', 'CCSCOFIRST');
define('CCS_CO_SECOND', 'CCSCOSECOND');
define('CONV_CO_FIRST', 'CONVCOFIRST');
define('CONV_CO_SECOND', 'CONVCOSECOND');
define('CONV_CO_CHITHAUPD', 'CONVCOCHITHAUPD');
define('CONV_CO_CHITHAUPD_COEND', 'CONVCOCHITHAUPDCOEND');
define('CONV_CO_REVERT', 'CONVCOREVERT');

//SK
define('NAME_CORR_SK_FIRST', 'NMECORRSKFIRST');
define('NAME_CORR_SK_SECOND', 'NMECORRSKSECOND');
define('NAME_CANC_SK_FIRST', 'NMECANCSKFIRST');
define('NAME_CANC_SK_SECOND', 'NMECANCSKSECOND');
define('CONV_SK_FIRST', 'CONVSKFIRST');
// define('CONV_SK_REVERT_DCEND', 'CONVSKREVERTDCEND');

//AST
define('NAME_CORR_AST_FIRST', 'NMECORRASTFIRST');
define('NAME_CANC_AST_FIRST', 'NMECANCASTFIRST');
define('CONV_AST_FIRST', 'CONVASTFIRST');
define('CONV_AST_PREMIUM_NOTICE', 'CONVASTPREMIUMNOTICE');
define('CONV_AST_CONFIRM_PREMIUM', 'CONVASTCONFIRMPREMIUM');
define('CONV_AST_SECOND', 'CONVASTSECOND');
// define('CONV_AST_REVERT_DCEND', 'CONVASTREVERTDCEND');

//BO
define('CONV_BO_FIRST', 'CONVBOFIRST');
define('CONV_BO_SECOND', 'CONVBOSECOND');
define('CONV_BO_CONFPREM', 'CONVBOCONFPREM');

//DC
define('CONV_DC_FIRST', 'CONVDCFIRST');
define('CONV_DC_SECOND', 'CONVDCSECOND');
define('CONV_DC_FINALORD', 'CONVDCFINALORD');
define('CONV_DC_DEPT_REPORT', 'CONVDCDEPTREPORT');

//ADC
define('CONV_ADC_FIRST', 'CONVADCFIRST');
define('CONV_ADC_SECOND', 'CONVADCSECOND');
define('CONV_ADC_FINALORD', 'CONVADCFINALORD');

?>